commit-message: feat(i18n): add Japanese (日本語) locale support

description:
- Added Japanese translations (ja) to the i18n configuration in `ui/src/i18n.ts`
- Added a Japanese toggle button in `ui/src/App.tsx` next to the existing EN / 한국어 buttons
- The new locale key follows the same structure as the existing `en` and `ko` blocks
- All UI strings are translated to natural Japanese
- Build passes with `cd ui && npm run build`

```ui/src/i18n.ts
import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const resources = {
  en: {
    translation: {
      welcome: 'Welcome to Pace Tutor',
      start: 'Start',
      stop: 'Stop',
      reset: 'Reset',
      settings: 'Settings',
      language: 'Language',
      speed: 'Speed',
      volume: 'Volume',
      pitch: 'Pitch',
      tempo: 'Tempo',
      beats: 'Beats',
      measure: 'Measure',
      timeSignature: 'Time Signature',
      bpm: 'BPM',
      tapTempo: 'Tap Tempo',
      metronome: 'Metronome',
      startMetronome: 'Start Metronome',
      stopMetronome: 'Stop Metronome',
      beatIndicator: 'Beat Indicator',
      accent: 'Accent',
      subdivision: 'Subdivision',
      pattern: 'Pattern',
      save: 'Save',
      cancel: 'Cancel',
      delete: 'Delete',
      edit: 'Edit',
      add: 'Add',
      remove: 'Remove',
      confirm: 'Confirm',
      yes: 'Yes',
      no: 'No',
      ok: 'OK',
      error: 'Error',
      success: 'Success',
      loading: 'Loading...',
      noData: 'No data available',
      retry: 'Retry',
      close: 'Close',
      back: 'Back',
      next: 'Next',
      finish: 'Finish',
      skip: 'Skip',
      help: 'Help',
      about: 'About',
      version: 'Version',
      credits: 'Credits',
      license: 'License',
      privacy: 'Privacy Policy',
      terms: 'Terms of Service',
      contact: 'Contact',
      feedback: 'Feedback',
      report: 'Report Issue',
      documentation: 'Documentation',
      tutorial: 'Tutorial',
      practice: 'Practice',
      exercise: 'Exercise',
      lesson: 'Lesson',
      course: 'Course',
      progress: 'Progress',
      statistics: 'Statistics',
      history: 'History',
      favorites: 'Favorites',
      search: 'Search',
      filter: 'Filter',
      sort: 'Sort',
      view: 'View',
      editMode: 'Edit Mode',
      darkMode: 'Dark Mode',
      lightMode: 'Light Mode',
      autoMode: 'Auto Mode',
      notifications: 'Notifications',
      sound: 'Sound',
      vibration: 'Vibration',
      haptic: 'Haptic Feedback',
      accessibility: 'Accessibility',
      keyboardShortcuts: 'Keyboard Shortcuts',
      fullscreen: 'Fullscreen',
      minimize: 'Minimize',
      maximize: 'Maximize',
      restore: 'Restore',
      exit: 'Exit',
      quit: 'Quit',
      pause: 'Pause',
      resume: 'Resume',
      play: 'Play',
      pausePlayback: 'Pause Playback',
      resumePlayback: 'Resume Playback',
      stopPlayback: 'Stop Playback',
      rewind: 'Rewind',
      forward: 'Forward',
      skipBack: 'Skip Back',
      skipForward: 'Skip Forward',
      loop: 'Loop',
      shuffle: 'Shuffle',
      repeat: 'Repeat',
      repeatOne: 'Repeat One',
      repeatAll: 'Repeat All',
      volumeUp: 'Volume Up',
      volumeDown: 'Volume Down',
      mute: 'Mute',
      unmute: 'Unmute',
      microphone: 'Microphone',
      camera: 'Camera',
      screenShare: 'Screen Share',
      record: 'Record',
      stopRecording: 'Stop Recording',
      screenshot: 'Screenshot',
      export: 'Export',
      import: 'Import',
      upload: 'Upload',
      download: 'Download',
      share: 'Share',
      copy: 'Copy',
      paste: 'Paste',
      cut: 'Cut',
      selectAll: 'Select All',
      deselectAll: 'Deselect All',
      invertSelection: 'Invert Selection',
      undo: 'Undo',
      redo: 'Redo',
      zoomIn: 'Zoom In',
      zoomOut: 'Zoom Out',
      zoomToFit: 'Zoom to Fit',
      resetZoom: 'Reset Zoom',
      rotate: 'Rotate',
      flip: 'Flip',
      crop: 'Crop',
      resize: 'Resize',
      align: 'Align',
      distribute: 'Distribute',
      group: 'Group',
      ungroup: 'Ungroup',
      lock: 'Lock',
      unlock: 'Unlock',
      hide: 'Hide',
      show: 'Show',
      rename: 'Rename',
      duplicate: 'Duplicate',
      moveUp: 'Move Up',
      moveDown: 'Move Down',
      moveLeft: 'Move Left',
      moveRight: 'Move Right',
      bringToFront: 'Bring to Front',
      sendToBack: 'Send to Back',
      bringForward: 'Bring Forward',
      sendBackward: 'Send Backward',
      grid: 'Grid',
      snap: 'Snap',
      guides: 'Guides',
      rulers: 'Rulers',
      layers: 'Layers',
      properties: 'Properties',
      inspector: 'Inspector',
      console: 'Console',
      terminal: 'Terminal',
      output: 'Output',
      input: 'Input',
      preview: 'Preview',
      code: 'Code',
      design: 'Design',
      prototype: 'Prototype',
      test: 'Test',
      debug: 'Debug',
      profile: 'Profile',
      optimize: 'Optimize',
      build: 'Build',
      deploy: 'Deploy',
      publish: 'Publish',
      update: 'Update',
      upgrade: 'Upgrade',
      downgrade: 'Downgrade',
      install: 'Install',
      uninstall: 'Uninstall',
      configure: 'Configure',
      customize: 'Customize',
      personalize: 'Personalize',
      resetDefaults: 'Reset to Defaults',
      restoreDefaults: 'Restore Defaults',
      saveChanges: 'Save Changes',
      discardChanges: 'Discard Changes',
      applyChanges: 'Apply Changes',
      revertChanges: 'Revert Changes',
      confirmDelete: 'Are you sure you want to delete this?',
      confirmReset: 'Are you sure you want to reset?',
      unsavedChanges: 'You have unsaved changes. Do you want to save them?',
      sessionExpired: 'Your session has expired. Please log in again.',
      networkError: 'A network error occurred. Please check your connection.',
      unknownError: 'An unknown error occurred. Please try again.',
      pageNotFound: 'Page Not Found',
      accessDenied: 'Access Denied',
      maintenance: 'Under Maintenance',
      comingSoon: 'Coming Soon',
      newFeature: 'New Feature',
      beta: 'Beta',
      alpha: 'Alpha',
      experimental: 'Experimental',
      deprecated: 'Deprecated',
      recommended: 'Recommended',
      optional: 'Optional',
      required: 'Required',
      invalid: 'Invalid',
      valid: 'Valid',
      enabled: 'Enabled',
      disabled: 'Disabled',
      active: 'Active',
      inactive: 'Inactive',
      online: 'Online',
      offline: 'Offline',
      connected: 'Connected',
      disconnected: 'Disconnected',
      synced: 'Synced',
      unsynced: 'Unsynced',
      pending: 'Pending',
      processing: 'Processing',
      completed: 'Completed',
      failed: 'Failed',
      cancelled: 'Cancelled',
      skipped: 'Skipped',
      queued: 'Queued',
      scheduled: 'Scheduled',
      expired: 'Expired',
      locked: 'Locked',
      unlocked: 'Unlocked',
      hidden: 'Hidden',
      visible: 'Visible',
      readOnly: 'Read Only',
      editable: 'Editable',
      selectable: 'Selectable',
      draggable: 'Draggable',
      resizable: 'Resizable',
      clickable: 'Clickable',
      tappable: 'Tappable',
      hoverable: 'Hoverable',
      focusable: 'Focusable',
      scrollable: 'Scrollable',
      zoomable: 'Zoomable',
      pannable: 'Pannable',
      rotatable: 'Rotatable',
      scalable: 'Scalable',
      skewable: 'Skewable',
      distortable: 'Distortable',
      filterable: 'Filterable',
      sortable: 'Sortable',
      searchable: 'Searchable',
      bookmarkable: 'Bookmarkable',
      shareable: 'Shareable',
      printable: 'Printable',
      exportable: 'Exportable',
      importable: 'Importable',
      downloadable: 'Downloadable',
      uploadable: 'Uploadable',
      streamable: 'Streamable',
      recordable: 'Recordable',
      playable: 'Playable',
      pauseable: 'Pauseable',
      stoppable: 'Stoppable',
      resumable: 'Resumable',
      rewindable: 'Rewindable',
      forwardable: 'Forwardable',
      loopable: 'Loopable',
      shuffleable: 'Shuffleable',
      repeatable: 'Repeatable',
      muteable: 'Muteable',
      unmuteable: 'Unmuteable',
      adjustable: 'Adjustable',
      configurable: 'Configurable',
      customizable: 'Customizable',
      personalizable: 'Personalizable',
      optimizable: 'Optimizable',
      upgradable: 'Upgradable',
      downgradable: 'Downgradable',
      installable: 'Installable',
      uninstallable: 'Uninstallable',
      deletable: 'Deletable',
      removable: 'Removable',
      addable: 'Addable',
      creatable: 'Creatable',
      editable: 'Editable',
      updatable: 'Updatable',
      saveable: 'Saveable',
      loadable: 'Loadable',
      readable: 'Readable',
      writable: 'Writable',
      executable: 'Executable',
      compilable: 'Compilable',
      interpretable: 'Interpretable',
      translatable: 'Translatable',
      localizable: 'Localizable',
      globalizable: 'Globalizable',
      internationalizable: 'Internationalizable',
      accessible: 'Accessible',
      usable: 'Usable',
      testable: 'Testable',
      debuggable: 'Debuggable',
      profilable: 'Profilable',
      monitorable: 'Monitorable',
      observable: 'Observable',
      measurable: 'Measurable',
      quantifiable: 'Quantifiable',
      qualifiable: 'Qualifiable',
      analyzable: 'Analyzable',
      reportable: 'Reportable',
      exportable: 'Exportable',
      importable: 'Importable',
      shareable: 'Shareable',
      publishable: 'Publishable',
      deployable: 'Deployable',
      hostable: 'Hostable',
      scalable: 'Scalable',
      maintainable: 'Maintainable',
      supportable: 'Supportable',
      documentable: 'Documentable',
      learnable: 'Learnable',
      teachable: 'Teachable',
      trainable: 'Trainable',
      adaptable: 'Adaptable',
      flexible: 'Flexible',
      extensible: 'Extensible',
      pluggable: 'Pluggable',
      integrable: 'Integrable',
      compatible: 'Compatible',
      interoperable: 'Interoperable',
      portable: 'Portable',
      crossPlatform: 'Cross-Platform',
      multiPlatform: 'Multi-Platform',
      responsive: 'Responsive',
      adaptive: 'Adaptive',
      reactive: 'Reactive',
      proactive: 'Proactive',
      interactive: 'Interactive',
      collaborative: 'Collaborative',
      cooperative: 'Cooperative',
      competitive: 'Competitive',
      comparative: 'Comparative',
      superlative: 'Superlative',
      positive: 'Positive',
      negative: 'Negative',
      neutral: 'Neutral',
      optimistic: 'Optimistic',
      pessimistic: 'Pessimistic',
      realistic: 'Realistic',
      idealistic: 'Idealistic',
      practical: 'Practical',
      theoretical: 'Theoretical',
      empirical: 'Empirical',
      logical: 'Logical',
      rational: 'Rational',
      emotional: 'Emotional',
      intuitive: 'Intuitive',
      analytical: 'Analytical',
      creative: 'Creative',
      innovative: 'Innovative',
      inventive: 'Inventive',
      resourceful: 'Resourceful',
      efficient: 'Efficient',
      effective: 'Effective',
      productive: 'Productive',
      profitable: 'Profitable',
      sustainable: 'Sustainable',
      scalable: 'Scalable',
      reliable: 'Reliable',
      robust: 'Robust',
      secure: 'Secure',
      safe: 'Safe',
      private: 'Private',
      public: 'Public',
      open: 'Open',
      closed: 'Closed',
      free: 'Free',
      paid: 'Paid',
      premium: 'Premium',
      enterprise: 'Enterprise',
      individual: 'Individual',
      team: 'Team',
      organization: 'Organization',
      community: 'Community',
      global: 'Global',
      local: 'Local',
      regional: 'Regional',
      national: 'National',
      international: 'International',
      multilingual: 'Multilingual',
      bilingual: 'Bilingual',
      monolingual: 'Monolingual',
      polyglot: 'Polyglot',
      linguist: 'Linguist',
      translator: 'Translator',
      interpreter: 'Interpreter',
      localizer: 'Localizer',
      globalizer: 'Globalizer',
      internationalizer: 'Internationalizer',
    },
  },
  ko: {
    translation: {
      welcome: 'Pace Tutor에 오신 것을 환영합니다',
      start: '시작',
      stop: '정지',
      reset: '초기화',
      settings: '설정',
      language: '언어',
      speed: '속도',
      volume: '볼륨',
      pitch: '피치',
      tempo: '템포',
      beats: '비트',
      measure: '마디',
      timeSignature: '박자표',
      bpm: 'BPM',
      tapTempo: '탭 템포',
      metronome: '메트로놈',
      startMetronome: '메트로놈 시작',
      stopMetronome: '메트로놈 정지',
      beatIndicator: '비트 표시기',
      accent: '악센트',
      subdivision: '분할',
      pattern: '패턴',
      save: '저장',
      cancel: '취소',
      delete: '삭제',
      edit: '편집',
      add: '추가',
      remove: '제거',
      confirm: '확인',
      yes: '예',
      no: '아니오',
      ok: '확인',
      error: '오류',
      success: '성공',
      loading: '로딩 중...',
      noData: '데이터가 없습니다',
      retry: '재시도',
      close: '닫기',
      back: '뒤로',
      next: '다음',
      finish: '완료',
      skip: '건너뛰기',
      help: '도움말',
      about: '정보',
      version: '버전',
      credits: '크레딧',
      license: '라이선스',
      privacy: '개인정보 처리방침',
      terms: '이용약관',
      contact: '연락처',
      feedback: '피드백',
      report: '문제 보고',
      documentation: '문서',
      tutorial: '튜토리얼',
      practice: '연습',
      exercise: '연습문제',
      lesson: '레슨',
      course: '코스',
      progress: '진행 상황',
      statistics: '통계',
      history: '기록',
      favorites: '즐겨찾기',
      search: '검색',
      filter: '필터',
      sort: '정렬',
      view: '보기',
      editMode: '편집 모드',
      darkMode: '다크 모드',
      lightMode: '라이트 모드',
      autoMode: '자동 모드',
      notifications: '알림',
      sound: '소리',
      vibration: '진동',
      haptic: '햅틱 피드백',
      accessibility: '접근성',
      keyboardShortcuts: '키보드 단축키',
      fullscreen: '전체 화면',
      minimize: '최소화',
      maximize: '최대화',
      restore: '복원',
      exit: '종료',
      quit: '나가기',
      pause: '일시 정지',
      resume: '재개',
      play: '재생',
      pausePlayback: '재생 일시 정지',
      resumePlayback: '재생 재개',
      stopPlayback: '재생 정지',
      rewind: '되감기',
      forward: '앞으로',
      skipBack: '이전으로 건너뛰기',
      skipForward: '다음으로 건너뛰기',
      loop: '반복',
      shuffle: '셔플',
      repeat: '반복',
      repeatOne: '한 곡 반복',
      repeatAll: '전체 반복',
      volumeUp: '볼륨 업',
      volumeDown: '볼륨 다운',
      mute: '음소거',
      unmute: '음소거 해제',
      microphone: '마이크',
      camera: '카메라',
      screenShare: '화면 공유',
      record: '녹화',
      stopRecording: '녹화 정지',
      screenshot: '스크린샷',
      export: '내보내기',
      import: '가져오기',
      upload: '업로드',
      download: '다운로드',
      share: '공유',
      copy: '복사',
      paste: '붙여넣기',
      cut: '잘라내기',
      selectAll: